### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "profileImageUrl": "https://cdn.example.com/profiles/user123.jpg",
  "loginId": "jaehyun99",
  "password": "securePass!2025",
  "phoneNumber": "010-8765-4321",
  "email": "jaehyun.kim99@example.com",
  "name": "김재현",
  "birthday": "1999-09-15"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "loginId": "jaehyun99",
  "password": "securePass!2025"
}

> {%
    client.global.set("accessToken", "Bearer " + response.body.data.accessToken);
%}


### 스터디 생성 (공개방)
POST http://localhost:8080/api/studies
Authorization: {{accessToken}}
Content-Type: application/json

{
  "studyName": "정처기",
  "coverImage": "image_url.jpg",
  "category": "LICENSE",
  "description": "정처기따요",
  "memberLimit": 2,
  "isPublic": true,
  "password": null
}


### 스터디 생성 (비공개방)
POST http://localhost:8080/api/studies
Authorization: {{accessToken}}
Content-Type: application/json

{
  "studyName": "06-12 임용송이 오전 공부반",
  "coverImage": "image_url.jpg",
  "category": "TEACHER_EXAM",
  "description": "눈송이 인증 받아요",
  "memberLimit": 2,
  "isPublic": false,
  "password": "060522"
}


### 스터디 접속(공개방)
POST http://localhost:8080/api/studies/1/participating/public
Authorization: {{accessToken}}
Content-Type: application/json


