### 카테고리 수정 (이름만 수정)
PATCH http://localhost:8080/api/todo-categories/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "운동"
}

### 카테고리 수정 (색상만 수정)
PATCH http://localhost:8080/api/todo-categories/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "color": "#00C2FF"
}

### (400) 둘 다 비어있음
PATCH http://localhost:8080/api/todo-categories/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}

