### 투두 수정 (제목 + 카테고리 변경)
PATCH http://localhost:8080/api/todos/1
Authorization: {{accessToken}}
Content-Type: application/json

{
  "title": "운영체제 과제하기 (수정)",
  "categoryId": 4
}

### 투두 수정 (제목만 변경)
PATCH http://localhost:8080/api/todos/1
Authorization: {{accessToken}}
Content-Type: application/json

{
  "title": "운영체제 과제하기 (제목만 수정)"
}

### 투두 수정 (body 비었을 때 → 400 기대)
PATCH http://localhost:8080/api/todos/101
Authorization: {{accessToken}}
Content-Type: application/json

{}

###---------투두 상태 변화 API------------

### 투두 상태 DONE 으로 변경
PATCH http://localhost:8080/api/todos/1/status
Authorization: {{accessToken}}
Content-Type: application/json

{
  "status": "DONE"
}

### 투두 상태 FAILED 로 변경
PATCH http://localhost:8080/api/todos/1/status
Authorization: {{accessToken}}
Content-Type: application/json

{
  "status": "FAILED"
}

### 잘못된 status 값 (400 Bad Request 기대)
PATCH http://localhost:8080/api/todos/1/status
Authorization: {{accessToken}}
Content-Type: application/json

{
  "status": "PENDING"
}
