@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWVoeXVuOTkiLCJpYXQiOjE3Njc0MjE2NDgsImV4cCI6MTc2NzQyNTI0OH0.2twvrIkjeOMJrW_9WM6jUNkmiGSCsHKiA5EgC4vU4R0

### 투두 카테고리 생성
POST http://localhost:8080/api/todo-categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "운동",
  "color": "#43434"
}

### 카테고리 삭제
DELETE http://localhost:8080/api/todo-categories/1
Authorization: Bearer {{accessToken}}

### 카테고리 목록 조회
GET http://localhost:8080/api/todo-categories
Authorization: Bearer {{accessToken}}

### 카테고리 수정 (이름만 수정)
PATCH http://localhost:8080/api/todo-categories/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "운동"
}

### 카테고리 수정 (색상만 수정)
PATCH http://localhost:8080/api/todo-categories/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "color": "#00C2FF"
}

### 카테고리 수정 (400) 둘 다 비어있음
PATCH http://localhost:8080/api/todo-categories/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}
###투두 생성 API
POST http://localhost:8080/api/todos
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "운동 30분 하기",
  "date": "2025-11-19",
  "categoryId": 1
}


### 특정 날짜 투두 목록 조회 (카테고리 없음)
GET http://localhost:8080/api/todos?date=2025-11-19
Authorization: Bearer {{accessToken}}

### 특정 날짜 투두 목록 조회 (카테고리 포함)
GET http://localhost:8080/api/todos?date=2025-10-31&categoryId=3
Authorization: Bearer {{accessToken}}

###투두 삭제 API
DELETE http://localhost:8080/api/todos/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}

### 투두 수정 (제목 + 카테고리 변경)
PATCH http://localhost:8080/api/todos/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "운영체제 과제하기 (수정)",
  "categoryId": 1
}

### 투두 수정 (제목만 변경)
PATCH http://localhost:8080/api/todos/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "운영체제 과제하기 (제목만 수정)"
}

### 투두 수정 (body 비었을 때 → 400 기대)
PATCH http://localhost:8080/api/todos/101
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}

###---------투두 상태 변화 API------------

### 투두 상태 DONE 으로 변경
PATCH http://localhost:8080/api/todos/1/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "DONE"
}

### 투두 상태 FAILED 로 변경
PATCH http://localhost:8080/api/todos/1/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "FAILED"
}

### 잘못된 status 값 (400 Bad Request 기대)
PATCH http://localhost:8080/api/todos/1/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "PENDING"
}
