POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "profileImageUrl": "https://cdn.example.com/profiles/user123.jpg",
  "loginId": "jaehyun99",
  "password": "securePass!2025",
  "phoneNumber": "010-8765-4321",
  "email": "jaehyun.kim99@example.com",
  "name": "김재현",
  "birthday": "1999-09-15"
}

