### test 의도
### 1. 사람1: 게시글 & 댓글 생성
### 2. 사람2: 사람1 게시글에 댓글 생성
### 3. 사람1에게 댓글 생성 알림 갔는지 확인

### 회원가입 (사람1)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "profileImageUrl": "https://cdn.example.com/profiles/user123.jpg",
  "loginId": "jaehyun99",
  "password": "securePass!2025",
  "phoneNumber": "010-8765-4321",
  "email": "jaehyun.kim99@example.com",
  "name": "김재현",
  "birthday": "1999-09-15"
}

### 회원가입 (사람2)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
"profileImageUrl": "https://cdn.example.com/profiles/user456.jpg",
"loginId": "soojin_dev",
"password": "MySecurePwd#2025",
"phoneNumber": "010-2222-3333",
"email": "soojin.dev@example.com",
"name": "박수진",
"birthday": "1995-04-22"
}

### 로그인 (사람1)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "loginId": "jaehyun99",
  "password": "securePass!2025"
}

> {%
    client.global.set("accessToken", "Bearer " + response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}


### 1. 사람1: 게시글 & 댓글 생성
### 게시글 생성 (사람1)
POST http://localhost:8080/api/posts
Authorization: {{accessToken}}
Content-Type: application/json

{
  "memberId": 1,
  "type": "인증",
  "title": "오늘의 스터디2",
  "content": {
    "text": "자료구조 스터디 완료",
    "imageUrls": [
      "https://storage.com/aaa.jpg",
      "https://storage.com/bbb.jpg"
    ]
  }
}

### 댓글 생성 (사람1)
POST http://localhost:8080/api/posts/1/comments
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "사람1 댓글",
  "isSecret": false
}


### 2. 사람2: 사람1 게시글에 댓글 생성
### 로그인 (사람2)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "loginId": "jaehyun99",
  "password": "securePass!2025"
}

> {%
    client.global.set("accessToken", "Bearer " + response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 댓글 생성 (사람2)
POST http://localhost:8080/api/posts/1/comments
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "사람2 댓글",
  "isSecret": false
}

### 로그인 (사람1)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "loginId": "jaehyun99",
  "password": "securePass!2025"
}

> {%
    client.global.set("accessToken", "Bearer " + response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}


### 3. 사람1에게 댓글 생성 알림 갔는지 확인
### 댓글 알림 조회 (사람1)
GET http://localhost:8080/api/notifications
Authorization: {{accessToken}}
Content-Type: application/json